apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  controllerUrl: "http://openshift-2072nosshcon-deye54z3.appd-cx.com:8090"
  account: "customer1"
  appName: "MyOSCluster"
  serviceAccountName: appdynamics-cluster-agent
  image: "docker.io/appdynamics/cluster-agent:20.7.0"
  nsToMonitor: [appdynamics,default,dev,stage]
