apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: employment-services
  name: employment-services
spec:
  selector:
    matchLabels:
      name: employment-services
  template:
    metadata:
      labels:
        name: employment-services
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: agent-config
        env:
        - name: APPDYNAMICS_AGENT_TIER_NAME
          value: WildFly
        - name: APPDYNAMICS_AGENT_UNIQUE_HOST_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName  

        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: appd-key
              name: appd-secret
        - name: APPDYNAMICS_AGENT_APPLICATION_NAME
          value: Employee_Service
        - name: JAVA_OPTS
          value: ' -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true  
            -Djboss.modules.system.pkgs="org.jboss.byteman,com.singularity" 
            -Dappdynamics.agent.accountAccessKey=$(APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY)
            -Dappdynamics.controller.hostName=$(APPDYNAMICS_CONTROLLER_HOST_NAME)
            -Dappdynamics.agent.uniqueHostId=$(APPDYNAMICS_AGENT_UNIQUE_HOST_ID)
            -Dappdynamics.controller.port=$(APPDYNAMICS_CONTROLLER_PORT) -Dappdynamics.controller.ssl.enabled=$(APPDYNAMICS_CONTROLLER_SSL_ENABLED)
            -Dappdynamics.agent.accountName=$(APPDYNAMICS_AGENT_ACCOUNT_NAME) -Dappdynamics.agent.applicationName=$(APPDYNAMICS_AGENT_APPLICATION_NAME)
            -Dappdynamics.agent.tierName=$(APPDYNAMICS_AGENT_TIER_NAME) -Dappdynamics.agent.reuse.nodeName=true
            -Dappdynamics.agent.reuse.nodeName.prefix=$(APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX) -javaagent:/opt/appdynamics-java/javaagent.jar '
        image: iogbole/wildfly-springboot-app #iogbole/wildfly-app
        imagePullPolicy: IfNotPresent
        name: employment-services
        ports:
        - containerPort: 8080
        - containerPort: 9990
        - containerPort: 7600
        - containerPort: 8888
        resources: {}
        volumeMounts:
        - mountPath: /opt/appdynamics-java
          name: appd-agent-repo-java
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - cp
        - -ra
        - /opt/appdynamics/.
        - /opt/temp
        image: docker.io/appdynamics/java-agent:20.7.0
        imagePullPolicy: IfNotPresent
        name: appd-agent-attach
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/temp
          name: appd-agent-repo-java
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: appd-agent-repo-java

---
apiVersion: v1
kind: Service
metadata:
  name: web-front-end
spec:
  selector:
    name: employment-services
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  type: NodePort
